credentials:
  usernames:
    titilayo.grace:
      name: Titilayo Grace
      password: ckdproject@1
    nwaigwe.amarachi:
      name: Nwaigwe Amarachi
      password: ckdproject@1
    ogundijo.bisola:
      name: Ogundijo Bisola
      password: ckdproject@1
    reviewer1:
      name: Admin
      password: ckdproject@123
cookie:
  name: renhealthckd
  key: some_random_key
  expiry_days: 30
preauthorized:
  emails: []