credentials:
  usernames:
    enumerator_user1:
      name: Enumerator 1
      password: ckdproject@1
    enumerator_user2:
      name: Enumerator 2
      password: ckdproject@1
    enumerator_user3:
      name: Enumerator 3
      password: ckdproject@1
    reviewer1:
      name: Sekoni Julian
      password: ckdproject@1
cookie:
  name: renhealthckd
  key: some_random_key
  expiry_days: 30
preauthorized:
  emails: []